CALLBACKS = {
    "CATALOG": "catalog",
    "CATEGORY": "cat",
    "PRODUCT": "prod",
    "ADD_TO_CART": "add",
    "VIEW_CART": "cart",
    "REMOVE_FROM_CART": "rm",
    "CLEAR_CART": "clear_cart",
    "CHECKOUT": "checkout",
    "CHECKOUT_CONFIRM": "checkout_confirm",
    "APPLY_PROMO": "apply_promo",
    "CANCEL_PROMO": "cancel_promo",
    "ADMIN_PANEL": "admin_panel",
    "ADMIN_ADD_PRODUCT": "admin_add",
    "ADMIN_LIST_PRODUCTS": "admin_list",
    "ADMIN_DELETE_PRODUCT": "admin_del",
    "ADMIN_ORDERS": "admin_orders",
    "ADMIN_ORDER_DETAIL": "admin_order",
    "ADMIN_ORDER_CONFIRM": "admin_oconfirm",
    "ADMIN_ORDER_CANCEL": "admin_ocancel",
    "ADMIN_ORDER_DONE": "admin_odone",
    "ADMIN_PROMOS": "admin_promos",
    "ADMIN_ADD_PROMO": "admin_add_promo",
    "ADMIN_DELETE_PROMO": "admin_del_promo",
    "ADMIN_PROMO_PERCENT": "admin_promo_pct",
    "ADMIN_PROMO_FIXED": "admin_promo_fix",
}
